### PR TITLE
feat: type for module

### PR DESCRIPTION
**Pull request by danielroe**
This adds minimal TypeScript support.

### CODE REVIEW

**Comment by danielroe** [comment]
@googlebot I signed it!

**Comment by developit** [comment]
Hi @danielroe - I am wondering if you know of a way to have this import the existing typings for `Worker` from TypeScript's `dom.d.ts`. I'm not super handy with TS definitions, but I think that might be the way for us to ensure this module remains transparent.

**Comment by danielroe** [comment]
@developit Couldn't agree more. But you wouldn't need to import it.

Someone who is consuming this library will probably already have a `tsconfig` that includes:

```json
{
  "compilerOptions": {
    "lib": ["dom"]
  }
}
```

Given that, the `index.d.ts` I've proposed here will inform TS that your module can be instantiated to return a Worker, according to the type defined in the `dom` library.

**Comment by developit** [comment]
Oh, awesome! That seems obvious now from looking at the code, apologies for my misinterpretation.

**Pull request merged**
